### ISSUE TITLE
Vue 实例存储全局数据作用？

### ISSUE THREAD

**Issue by majianxiong** [platojs/system#3]
![image](https://cloud.githubusercontent.com/assets/887531/23785921/038f2906-05a5-11e7-88c5-5cb7c7255bac.png)
```javascript
export default data => {
  // create context
  return Object.assign(new Vue({}), data, { Vue })
}
```
这里说到用Vue的实例来挂载配置属性，可以方便使用其事件订阅特性，是指的[vue global event bus](https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication)吗？

**Comment by crossjs** [comment]
是。

当然不仅仅是这些
