### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by majianxiong** [platojs/system#4]
![image](https://cloud.githubusercontent.com/assets/887531/23937269/90b8333c-0991-11e7-9d98-2db0c141bac9.png)
使用的是Win7 64位系统，怎么会出现这个问题

**Comment by majianxiong** [comment]
with rimraf:
```
rimraf node_modules/
```
and re-adding all dependencies:
```
npm i
```
通过上述方法解决了该问题

**Comment by crossjs** [comment]
嗯。应该是依赖项没有升级到可用的版本。
这个问题是后续要解决的，beta 阶段暂不处理。

**Comment by crossjs** [comment]
已使用 npm-shrinkwrap 来锁定依赖项的版本号
https://github.com/platojs/plato/commit/5528fa0a9ec28713146f9ed5c90b010d3f12a422
