### ISSUE TITLE
PhantomJS was not killed in 2000 ms, sending SIGKILL.

### ISSUE THREAD

**Issue by majianxiong** [platojs/system#5]
![image](https://cloud.githubusercontent.com/assets/887531/23938582/dd70995c-0997-11e7-8f9e-0c774ef17999.png)
环境win7 64位系统

**Comment by crossjs** [comment]
手头没有 Win 7 系统。
在 Win 10 下测试正常。

**Comment by majianxiong** [comment]
![image](https://cloud.githubusercontent.com/assets/887531/24072732/5f2d0c6a-0c26-11e7-8eab-342785d0c66b.png)
这个属于正常吗
