### ISSUE TITLE
组件 options 注入数据问题

### ISSUE THREAD

**Issue by majianxiong** [platojs/system#6]
组件注册示例：
![image](https://cloud.githubusercontent.com/assets/887531/25077216/4c5b5efc-235a-11e7-8771-9becffcc66fb.png)
![image](https://cloud.githubusercontent.com/assets/887531/25077223/66e45814-235a-11e7-8ca2-9d8c752fad61.png)

通过以上方式，会进入else，但是这种方式，无法完成scope的注入
![image](https://cloud.githubusercontent.com/assets/887531/25077198/1ae2601e-235a-11e7-8948-e91b5f8a382f.png)

**Comment by crossjs** [comment]
OK。我们需要验证下对同步模块的注入

**Comment by crossjs** [comment]
为了保持简单与一致性，不考虑支持通过 Vue.component 直接定义的组件。
请使用推荐的最佳实践：https://vuejs.org/v2/guide/single-file-components.html
